"""Built-in training presets, extracted from the original tkinter screens.

These mirror the _BUILTIN_TEMPLATES dicts in screens/train_il.py and
screens/train_rl.py so the new Tauri frontend can offer the same templates
without re-importing the tkinter modules (which require ttk at import time).
"""


BUILTIN_PRESETS: dict[str, dict[str, dict]] = {
    "imitation": {
        "Default (all defaults)": {},
        "Imitation Example": {
            "runtime.max_runtime": 518400,
            "runtime.log_interval": 300,
            "runtime.save_interval": 600,
            "runtime.eval_every_n": 5000,
            "runtime.num_eval_steps": 200,
            "dataset.data_dir": "",
            "dataset.meta_path": "",
            "dataset.allowed_characters": "fox",
            "dataset.allowed_opponents": "all",
            "data.batch_size": 512,
            "data.unroll_length": 80,
            "learner.learning_rate": 1e-4,
            "learner.reward_halflife": 4,
            "network.name": "tx_like",
            "network.tx_like.num_layers": 3,
            "network.tx_like.hidden_size": 512,
            "network.tx_like.ffw_multiplier": 2,
            "policy.train_value_head": False,
            "policy.delay": 18,
            "value_function.train_separate_network": True,
            "value_function.separate_network_config": True,
            "value_function.network.name": "tx_like",
            "value_function.network.tx_like.num_layers": 1,
            "value_function.network.tx_like.hidden_size": 512,
            "value_function.network.tx_like.ffw_multiplier": 2,
            "controller_head.name": "autoregressive",
            "controller_head.autoregressive.component_depth": 2,
            "controller_head.autoregressive.residual_size": 128,
        },
    },
    "q_learning": {
        "Default (all defaults)": {},
    },
    "rl_single": {
        "Default (all defaults)": {},
        "RL Example (from scripts/rl_example.sh)": {
            "runtime.tag": "fox_delay_18",
            "runtime.max_step": 10000,
            "runtime.log_interval": 300,
            "runtime.reset_every_n_steps": 512,
            "runtime.burnin_steps_after_reset": 5,
            "learner.learning_rate": 3e-5,
            "learner.value_cost": 1,
            "learner.reward_halflife": 4,
            "learner.reward.damage_ratio": 0.01,
            "learner.reward.ledge_grab_penalty": 0.02,
            "learner.policy_gradient_weight": 5,
            "learner.kl_teacher_weight": 3e-3,
            "learner.ppo.num_epochs": 2,
            "learner.ppo.num_batches": 16,
            "learner.ppo.beta": 3e-1,
            "learner.ppo.epsilon": 1e-2,
            "learner.ppo.minibatched": False,
            "teacher": "",
            "opponent.type": "SELF",
            "opponent.train": True,
            "actor.rollout_length": 240,
            "actor.num_envs": 96,
            "actor.inner_batch_size": 8,
            "actor.async_envs": True,
            "actor.num_env_steps": 4,
            "actor.gpu_inference": True,
            "agent.name": "Master Player",
            "agent.batch_steps": 4,
            "optimizer_burnin_steps": 128,
            "value_burnin_steps": 128,
        },
        "Single-Agent vs Frozen Opponent": {
            "runtime.max_step": 10000000,
            "runtime.max_runtime": 518400,
            "runtime.log_interval": 300,
            "runtime.save_interval": 600,
            "runtime.reset_every_n_steps": 6144,
            "runtime.burnin_steps_after_reset": 5,
            "dolphin.infinite_time": True,
            "dolphin.headless": True,
            "dolphin.log_level": 3,
            "dolphin.console_timeout": 60,
            "learner.learning_rate": 3e-5,
            "learner.value_cost": 1,
            "learner.reward.damage_ratio": 0.01,
            "learner.reward.ledge_grab_penalty": 0.02,
            "learner.reward.stalling_penalty": 0.1,
            "learner.reward.stalling_threshold": 50.0,
            "learner.reward.voluntary_offstage_death_penalty": 0.6,
            "learner.reward_halflife": 8.0,
            "learner.reward.approaching_factor": 0.003,
            "learner.policy_gradient_weight": 3,
            "learner.kl_teacher_weight": 5e-2,
            "learner.reverse_kl_teacher_weight": 5e-2,
            "learner.ppo.num_epochs": 2,
            "learner.ppo.num_batches": 16,
            "learner.ppo.beta": 3e-1,
            "learner.ppo.epsilon": 1e-2,
            "learner.ppo.max_mean_actor_kl": 1e-4,
            "learner.ppo.minibatched": False,
            "opponent.type": "OTHER",
            "opponent.train": False,
            "actor.rollout_length": 60,
            "actor.num_envs": 120,
            "actor.inner_batch_size": 12,
            "actor.async_envs": True,
            "actor.num_env_steps": 4,
            "actor.gpu_inference": True,
            "agent.batch_steps": 4,
            "optimizer_burnin_steps": 128,
            "value_burnin_steps": 128,
        },
    },
    "rl_train_two": {
        "Default (all defaults)": {},
        "Two-Agent Fresh Start": {
            "runtime.max_step": 10000000,
            "runtime.max_runtime": 518400,
            "runtime.log_interval": 300,
            "runtime.save_interval": 600,
            "runtime.reset_every_n_steps": 6144,
            "runtime.burnin_steps_after_reset": 5,
            "dolphin.infinite_time": True,
            "dolphin.headless": True,
            "dolphin.log_level": 3,
            "dolphin.console_timeout": 60,
            "p1.batch_steps": 4,
            "p2.batch_steps": 4,
            "learner.learning_rate": 3e-5,
            "learner.value_cost": 1,
            "learner.reward.damage_ratio": 0.01,
            "learner.reward_halflife": 8.0,
            "learner.policy_gradient_weight": 3,
            "learner.kl_teacher_weight": 5e-2,
            "learner.reverse_kl_teacher_weight": 5e-2,
            "learner.ppo.num_epochs": 2,
            "learner.ppo.num_batches": 16,
            "learner.ppo.beta": 3e-1,
            "learner.ppo.epsilon": 1e-2,
            "learner.ppo.max_mean_actor_kl": 1e-4,
            "learner.ppo.minibatched": False,
            "learner1.reward.ledge_grab_penalty": 0.02,
            "learner1.reward.stalling_penalty": 0.1,
            "learner1.reward.stalling_threshold": 50.0,
            "learner1.reward.approaching_factor": 0.0,
            "learner1.reward.l_cancel_miss_penalty": 0,
            "learner1.reward.voluntary_offstage_death_penalty": 0.5,
            "learner2.learning_rate": 1e-5,
            "actor.rollout_length": 60,
            "actor.num_envs": 120,
            "actor.inner_batch_size": 12,
            "actor.async_envs": True,
            "actor.num_env_steps": 4,
            "actor.gpu_inference": True,
            "optimizer_burnin_steps": 128,
            "value_burnin_steps": 128,
        },
        "Two-Agent Multi-Character": {
            "runtime.max_step": 10000000,
            "runtime.max_runtime": 518400,
            "runtime.log_interval": 300,
            "runtime.save_interval": 600,
            "runtime.reset_every_n_steps": 6144,
            "runtime.burnin_steps_after_reset": 5,
            "dolphin.infinite_time": True,
            "dolphin.headless": True,
            "dolphin.log_level": 3,
            "dolphin.console_timeout": 60,
            "p1.batch_steps": 4,
            "p2.char": "FOX,FALCO,MARTH,SHEIK,JIGGLYPUFF,CPTFALCON,PEACH,YOSHI,POPO,LUIGI,PIKACHU,SAMUS",
            "p2.batch_steps": 4,
            "learner.learning_rate": 3e-5,
            "learner.value_cost": 1,
            "learner.reward.damage_ratio": 0.01,
            "learner.reward_halflife": 8.0,
            "learner.policy_gradient_weight": 3,
            "learner.kl_teacher_weight": 5e-2,
            "learner.reverse_kl_teacher_weight": 5e-2,
            "learner.ppo.num_epochs": 2,
            "learner.ppo.num_batches": 16,
            "learner.ppo.beta": 3e-1,
            "learner.ppo.epsilon": 1e-2,
            "learner.ppo.max_mean_actor_kl": 1e-4,
            "learner.ppo.minibatched": False,
            "learner1.reward.ledge_grab_penalty": 0.02,
            "learner1.reward.stalling_penalty": 0.1,
            "learner1.reward.stalling_threshold": 50.0,
            "learner1.reward.approaching_factor": 0.0,
            "learner1.reward.l_cancel_miss_penalty": 0,
            "learner1.reward.voluntary_offstage_death_penalty": 0.5,
            "learner2.learning_rate": 1e-5,
            "actor.rollout_length": 60,
            "actor.num_envs": 120,
            "actor.inner_batch_size": 12,
            "actor.async_envs": True,
            "actor.num_env_steps": 4,
            "actor.gpu_inference": True,
            "optimizer_burnin_steps": 128,
            "value_burnin_steps": 128,
        },
    },
}
